'visualization':
    'fig_format': 'png'     # Расширение графиков
    'fig_dpi': 300          # DPI графиков
    'show_title': True      # Отрисовка заголовков графиков
    'show_legend': False    # Отрисовка легенды графиков
    't_sign': 't, {0}с'     # Подпись по оси времени !!! Исправить
'devices':
    'GTLab D401':  # FIXME Правильное название и сигнатура
        'reading':
            'signature_1ch': 'FIXME'  # FIXME Заполнить
            'signature_2ch': 'time\t'
            'position': [0, 5]
        'processing':
            'invert': [False, False]                            # Инвертирование ch1 и ch2
            'time_shift': False                                 # Ликвидация смещения нуля по времени
            'channel_shift': False                              # Ликвидация смещения нуля по сигналу
            'channel_shift_amount': 1000                        # Число условно принятых за ноль первых элементов сигнала
            'time_limitation': False                            # Ограничение по времени
            'time_limits': [!!float NaN, !!float NaN]           # Левая и правая границы по времени
            'moving_average_smoothing': False                   # Сглаживание скользящей средней
            'moving_average_window': 1000                       # Ширина окна сглаживания
    'Gydropribor':  # FIXME Правильное название и сигнатура
        'reading':
            'signature_1ch': '   '
            'signature_2ch': 'FIXME'  # FIXME Заполнить
            'position': [0, 4]
        'processing':
            'invert': [False, False]
            'time_shift': False                                 # Ликвидация смещения нуля по времени
            'channel_shift': False                              # Ликвидация смещения нуля по сигналу
            'channel_shift_amount': 1000                        # Число условно принятых за ноль первых элементов сигнала
            'time_limitation': False                            # Ограничение по времени
            'time_limits': [!!float NaN, !!float NaN]           # Левая и правая границы по времени
            'moving_average_smoothing': False                   # Сглаживание скользящей средней
            'moving_average_window': 1000                       # Ширина окна сглаживания
    'Micsig tBook':
        'reading':
            'signature_1ch': 'ProID,Info,,time,Vo'
            'signature_2ch': 'ProID,Info,Unnamed: 2,time,Vol.,Unnamed: 5,ProID,Info,Unnamed: 2,time,Vol.,Unnamed'
            'position': [0, -4]
        'processing':
            'invert': [False, False]
            'time_shift': False                                 # Ликвидация смещения нуля по времени
            'channel_shift': False                              # Ликвидация смещения нуля по сигналу
            'channel_shift_amount': 1000                        # Число условно принятых за ноль первых элементов сигнала
            'time_limitation': False                            # Ограничение по времени
            'time_limits': [!!float NaN, !!float NaN]           # Левая и правая границы по времени
            'moving_average_smoothing': False                   # Сглаживание скользящей средней
            'moving_average_window': 1000                       # Ширина окна сглаживания
    'Rigol DS1000Z Series':
        'reading':
            'signature_1ch': 'X,CH1,Start,Increment'
            'signature_2ch': 'X,CH1,CH2,Start,Increment'
            'position': [0, -2]
        'processing':
            'invert': [False, False]
            'time_shift': False                                 # Ликвидация смещения нуля по времени
            'channel_shift': False                              # Ликвидация смещения нуля по сигналу
            'channel_shift_amount': 1000                        # Число условно принятых за ноль первых элементов сигнала
            'time_limitation': False                            # Ограничение по времени
            'time_limits': [!!float NaN, !!float NaN]           # Левая и правая границы по времени
            'moving_average_smoothing': False                   # Сглаживание скользящей средней
            'moving_average_window': 1000                       # Ширина окна сглаживания
    'Rigol DS1102E':
        'reading':
            'signature_1ch': 'Time,X(CH1)'
            'signature_2ch': 'Time,X(CH1),X(CH2)'  # !!! Снять
            'position': [0, -2]
        'processing':
            'invert': [False, False]
            'time_shift': False                                 # Ликвидация смещения нуля по времени
            'channel_shift': False                              # Ликвидация смещения нуля по сигналу
            'channel_shift_amount': 1000                        # Число условно принятых за ноль первых элементов сигнала
            'time_limitation': False                            # Ограничение по времени
            'time_limits': [!!float NaN, !!float NaN]           # Левая и правая границы по времени
            'moving_average_smoothing': False                   # Сглаживание скользящей средней
            'moving_average_window': 1000                       # Ширина окна сглаживания
    'Rigol DG4202':  # FIXME Предположительно. Файл импульса от КВГ. Что это за прибор? Узнать!
        'reading':
            'signature_1ch': 'X\tCH1\tStart\tIncrement'
            'signature_2ch': 'X\tCH1\tCH2\tStart\tIncrement'  # !!! Снять
            'position': [0, -2]
        'processing':
            'invert': [False, False]
            'time_shift': False                                 # Ликвидация смещения нуля по времени
            'channel_shift': False                              # Ликвидация смещения нуля по сигналу
            'channel_shift_amount': 1000                        # Число условно принятых за ноль первых элементов сигнала
            'time_limitation': False                            # Ограничение по времени
            'time_limits': [!!float NaN, !!float NaN]           # Левая и правая границы по времени
            'moving_average_smoothing': False                   # Сглаживание скользящей средней
            'moving_average_window': 1000                       # Ширина окна сглаживания
    'Tektronix MSO46':
        'reading':
            'signature_1ch': 'X,CH1,Start,Increment'  # !!! Снять
            'signature_2ch': 'X,CH1,CH2,Start,Increment'
            'position': [0, -1]
        'processing':
            'invert': [True, True]
            'time_shift': False                                 # Ликвидация смещения нуля по времени
            'channel_shift': False                              # Ликвидация смещения нуля по сигналу
            'channel_shift_amount': 1000                        # Число условно принятых за ноль первых элементов сигнала
            'time_limitation': False                            # Ограничение по времени
            'time_limits': [!!float NaN, !!float NaN]           # Левая и правая границы по времени
            'moving_average_smoothing': False                   # Сглаживание скользящей средней
            'moving_average_window': 1000                       # Ширина окна сглаживания

